  version: '3.7'

  services:
      backend:
        build:
          context: ./backend
          dockerfile: Dockerfile
        image: willylopezcontainers.azurecr.io/myapp-backend
        container_name: myapp-node-server
        command: /usr/src/app/node_modules/.bin/nodemon server.js
        volumes:
          - ./backend/:/usr/src/app
          - /usr/src/app/node_modules
        ports:
          - "8000:8000"
        env_file: ./backend/.env
        environment:
          - NODE_ENV=development
        networks:
          - app-network
        tty: true
      client:
        build:
          context: ./frontend
          dockerfile: Dockerfile
        image: willylopezcontainers.azurecr.io/myapp-frontend
        container_name: myapp-react-client
        command: npm start
        volumes:
          - ./frontend/:/usr/app
          - /usr/app/node_modules
        depends_on:
          - backend
        ports:
          - "3000:3000"
        networks:
          - app-network
        tty: true
          
  networks:
    app-network:
        driver: bridge
